In [104]:
import pandas as pd
import numpy as np

# Pubmed

Function to summarize

In [105]:
from pymed import PubMed

def loc_articles_Pubmed(query, max_results=500, verbose = True):
    pubmed = PubMed(tool="MyTool", email="my@email.address")
    q = query

    results = list(pubmed.query(q_pubmed, max_results=max_results))

    if verbose:
        print(f"Query used: ",query)
        print(f"Number of articles: ",len(results))

    pubmed_results = [article.toDict() for article in results]

    pubmed_results = pd.DataFrame(pubmed_results)   

    return pubmed_results

In [106]:
q_pubmed = '( "graph" OR "community detection " OR "group" OR "cluster") AND ( "relevance" OR "redundancy" ) AND ( "feature selection" OR "dimensionality reduction" ) AND ( "biological" OR "Gene expression" OR "transcriptomics" OR “RNA-seq” OR “array” )'

Pubmed_articles = loc_articles_Pubmed(query=q_pubmed)

pubmed_results.to_csv("PubmedArticles.csv")
pubmed_results.head()

Query used:  ( "graph" OR "community detection " OR "group" OR "cluster") AND ( "relevance" OR "redundancy" ) AND ( "feature selection" OR "dimensionality reduction" ) AND ( "biological" OR "Gene expression" OR "transcriptomics" OR “RNA-seq” OR “array” )
Number of articles:  114

,pubmed_id,title,abstract,keywords,journal,publication_date,authors,methods,conclusions,results,copyrights,doi,xml
0,41818906,A radiomics-driven approach for predicting res...,This work established and validated a radiomic...,"[Computed tomography, Delta radiomics, Feature...",European journal of radiology,2026-03-13,"[{'lastname': 'Qu', 'firstname': 'Zhonghui', '...",NaN,"CT-based Delta radiomics constitutes a robust,...",ISS staging (I/II/III: 19.9%/29.0%/51.1%) was ...,Copyright © 2026 The Authors. Published by Els...,10.1016/j.ejrad.2026.112779,"[[[], [<Element 'Year' at 0x7513da836c00>, <El..."
1,41653869,From unsupervised selection of AIMs to likelih...,Biogeographical ancestry (BGA) inference is an...,"[Ancestry informative markers, Biogeographical...",Forensic science international. Genetics,2026-02-08,"[{'lastname': 'Resutik', 'firstname': 'Peter',...",NaN,NaN,NaN,Copyright © 2026 The Authors. Published by Els...,10.1016/j.fsigen.2026.103433,"[[[], [<Element 'Year' at 0x75138be16e80>, <El..."
2,41639748\n26527291\n28263960\n30531897\n297849...,SAKURA: a knowledge-guided approach to recover...,Dimensionality reduction is routinely applied ...,[],Genome biology,2026-02-05,"[{'lastname': 'Zhang', 'firstname': 'Zhenghao'...",NaN,NaN,NaN,© 2026. The Author(s).,10.1186/s13059-026-03965-8\n10.1186/s13059-015...,"[[[], [<Element 'Year' at 0x75138be31e40>, <El..."
3,41611901\n20122224\n21706728\n19708770\n281284...,"Adaptive fuzzy cluster-guided simple, fast, an...","High-dimensional, highly imbalanced microarray...","[Binary imbalanced classification, Complexity ...",Scientific reports,2026-01-30,"[{'lastname': 'Tye', 'firstname': 'Yi Wei', 'i...",NaN,NaN,NaN,© 2026. The Author(s).,10.1038/s41598-026-37086-w\n10.1002/bmb.2004.4...,"[[[], [<Element 'Year' at 0x75138be51350>, <El..."
4,41568381\n21965334\n25114853\n30591591\n399792...,Integrative multi-omics stratification and tra...,Immunosuppressive breast cancer subtypes drive...,"[breast cancer, immunosuppressive tumormicroen...",Frontiers in oncology,2026-01-22,"[{'lastname': 'Kim', 'firstname': 'Nari', 'ini...",NaN,This study identifies Treg-enriched and immuno...,The C2 cluster exhibited elevated Treg-related...,"Copyright © 2026 Kim, Na, Lee, Yi, Son, Park, ...",10.3389/fonc.2025.1731411\n10.1172/JCI60534\n1...,"[[[], [<Element 'Year' at 0x75138be74900>, <El..."

# Scopus

My scopus Key: ab528db237c9103c9e4cee942f602c28

Generic function. You need a API key and possibly and institution token (not necessary inside UFRGS) to make the query.

In [107]:
import pybliometrics
from pybliometrics.scopus import ScopusSearch

def loc_articles_Scopus(query, verbose = True):
    pybliometrics.scopus.init()
    q = query

    results = ScopusSearch(q_scopus, verbose=True)

    scopus_results = pd.DataFrame(results.results)

    if verbose:
        print(f"Query used: ",query)
        print(f"Number of articles: ",len(scopus_results))

    scopus_results = pd.DataFrame(results.results)

    return scopus_results

In [108]:
q_scopus = 'TITLE-ABS-KEY ( ( "graph" OR "community detection " OR "group" OR "cluster") AND ( "relevance" OR "redundancy" ) AND ( "feature selection" OR "dimensionality reduction" ) AND ( "biological" OR "Gene expression" OR "transcriptomics" OR “RNA-seq” OR “array” ))'

scopus_results = loc_articles_Scopus(q_scopus)

scopus_results.head()
scopus_results.to_csv("ScopusArticles.csv")

Query used:  TITLE-ABS-KEY ( ( "graph" OR "community detection " OR "group" OR "cluster") AND ( "relevance" OR "redundancy" ) AND ( "feature selection" OR "dimensionality reduction" ) AND ( "biological" OR "Gene expression" OR "transcriptomics" OR “RNA-seq” OR “array” ))
Number of articles:  316

# Semantic Scholar

In [109]:
# First, import the client from semanticscholar module
from semanticscholar import SemanticScholar

# You'll need an instance of the client to request data from the API
sch = SemanticScholar()

In [110]:
#q_semanticScholar = '( "graph" OR "community detection" OR "group" OR "cluster" ) AND ( "relevance" OR "redundancy" ) AND ( "feature selection" OR "dimensionality reduction" ) AND ( "biological" OR "Gene expression" OR "omics" )'

response = sch.search_paper(query=q_semanticScholar, bulk=True, sort='publicationDate:desc')

len(response)

1000

In [111]:
q_semanticScholar = "graph feature selection"

response = sch.search_paper(query=q_semanticScholar, bulk=True, sort='publicationDate:desc')

len(response)

1000

In [112]:
all_results = []
i = 1
for item in response:
    all_results.append(item)
    i += 1

len(all_results)

4761

In [113]:
semantic_scholar_df = pd.DataFrame([paper.raw_data for paper in all_results])

In [114]:
from semanticscholar import SemanticScholar

sch = SemanticScholar()

In [ ]:
from semanticscholar import SemanticScholar

def loc_articles_SemanticScholar(query, verbose = True):
    q = query

    results = sch.search_paper(query=query, bulk=True, sort='publicationDate:desc')

    all_results = []
    i = 1
    for item in results:
        all_results.append(item)
        i += 1

    if verbose:
        print(f"Query used: ",query)
        print(f"Number of articles: ",len(all_results))

    SemanticScholar_results = pd.DataFrame([paper.raw_data for paper in all_results])

    return SemanticScholar_results

In [116]:
q_sscholar = "graph feature selection"

semanticScholar_results = loc_articles_SemanticScholar(q_sscholar)

semanticScholar_results.head()
semanticScholar_results.to_csv("SemanticScholarArticles.csv")

Query used:  graph feature selection
Number of articles:  4761

In [131]:
semanticScholar_results.head()

,paperId,externalIds,corpusId,publicationVenue,url,title,venue,year,referenceCount,citationCount,...,isOpenAccess,openAccessPdf,fieldsOfStudy,s2FieldsOfStudy,publicationTypes,publicationDate,journal,citationStyles,authors,abstract
0,acedfb49a1a2f126d7323e8b08e13bad477dfd39,"{'DBLP': 'journals/ipm/ZhouNQLZL26', 'DOI': '1...",283815506,"{'id': '37f5b9b7-f828-4ae1-a174-45b538cbd4e4',...",https://www.semanticscholar.org/paper/acedfb49...,MetaPFS: Memory-efficient node classification ...,Information Processing & Management,2026.0,43,0,...,False,"{'url': '', 'status': None, 'license': None, '...",[Computer Science],"[{'category': 'Computer Science', 'source': 'e...",[JournalArticle],2026-04-01,"{'name': 'Inf. Process. Manag.', 'pages': '104...","{'bibtex': '@Article{Zhou2026MetaPFSMN, autho...","[{'authorId': '2395687596', 'name': 'Yuewei Zh...",NaN
1,0d60bed15d9a59ba7764d1101cb1615d4c9a92cd,"{'ArXiv': '2603.20829', 'CorpusId': 286762414}",286762414,None,https://www.semanticscholar.org/paper/0d60bed1...,Beyond the Academic Monoculture: A Unified Fra...,,2026.0,0,0,...,False,"{'url': '', 'status': None, 'license': None, '...",[Computer Science],"[{'category': 'Computer Science', 'source': 'e...",[Review],2026-03-21,None,"{'bibtex': '@Inproceedings{Liu2026BeyondTA, a...","[{'authorId': None, 'name': 'Yunhui Liu'}, {'a...",Attributed Graph Clustering (AGC) is a fundame...
2,65e9ad4709ffc980837110bcc0b33795d06fa001,"{'DOI': '10.1093/jcde/qwag026', 'CorpusId': 28...",286732967,"{'id': 'e09f8f4e-50bb-475c-8a00-46f853d8c6c9',...",https://www.semanticscholar.org/paper/65e9ad47...,Analysis of Geometric Feature Importance for E...,Journal of Computational Design and Engineering,2026.0,0,0,...,False,"{'url': '', 'status': None, 'license': None, '...",None,"[{'category': 'Engineering', 'source': 's2-fos...",[JournalArticle],2026-03-20,{'name': 'Journal of Computational Design and ...,"{'bibtex': '@Article{Lee2026AnalysisOG, autho...","[{'authorId': '2145232549', 'name': 'Kwangho L...",\n Injection-moulding computer-aided engineeri...
3,1bf14994dda1dcd4e63cc20c66f7c304deb59367,"{'DOI': '10.11124/JBIES-25-00259', 'CorpusId':...",286681494,"{'id': 'e90ec288-bb87-462f-9a2a-9d49aebebb7c',...",https://www.semanticscholar.org/paper/1bf14994...,Models and input parameters for the estimation...,JBI Evidence Synthesis,2026.0,211,0,...,False,"{'url': '', 'status': None, 'license': None, '...",[Medicine],"[{'category': 'Medicine', 'source': 'external'...","[JournalArticle, Review]",2026-03-20,{'name': 'JBI evidence synthesis'},"{'bibtex': '@Article{Kovács2026ModelsAI, auth...","[{'authorId': '2015580867', 'name': 'B. Kovács...",OBJECTIVE\nThis scoping review aims to identif...
4,dec45b2739f21477636eae5676e791f362a6dd5e,"{'DOI': '10.1088/1361-6501/ae54be', 'CorpusId'...",286747676,"{'id': '80f85f47-9f79-4683-b9e0-9df43c2cc065',...",https://www.semanticscholar.org/paper/dec45b27...,Dynamic causal decoupling network based on int...,Measurement science and technology,2026.0,0,0,...,False,"{'url': '', 'status': None, 'license': None, '...",None,"[{'category': 'Engineering', 'source': 's2-fos...",[JournalArticle],2026-03-19,{'name': 'Measurement Science and Technology'},"{'bibtex': '@Article{Liu2026DynamicCD, author...","[{'authorId': '2144165796', 'name': 'jianlong ...",\n Most existing fault diagnosis methods for c...

# IEEE Xplore

In [ ]:
from xploreapi.xploreapi import XPLORE

def loc_articles_IEEEXplore(query, API_key, max_results = 2000, verbose = True):
    q = query
    key = API_key

    rquery = XPLORE('API_key')
    query.searchField('boolean_text', query)
    query.maximumResults(max_results)
    query.resultsSorting('publication_year','asc')
    query.dataFormat("object")

    data = query.callAPI()

    raw_ieee_df = pd.DataFrame(data.get("articles", []))

    if verbose:
        print(f"Query used: ",query)
        print(f"Number of articles: ",len(raw_ieee_df))

    return raw_ieee_df

In [ ]:
ieee_q = '"feature selection" AND "graph"'
ieee_key = 'sgn9yv22tpzvs94h86szym79'

ieee_results = loc_articles_IEEEXplore(q_sscholar, API_key = ieee_key)

ieee_results.head()
ieee_results.to_csv("IEEEXploreArticles.csv")

AttributeError: 'str' object has no attribute 'searchField'

In [ ]:
query = XPLORE('sgn9yv22tpzvs94h86szym79')
query.searchField('boolean_text', '"feature selection" AND "graph"')
query.maximumResults(2000)
query.resultsSorting('publication_year','asc')
query.dataFormat("object")